# Task 1: Data Cleaning and Preprocessing
## Customer Churn Analysis and Prediction — SaiKet Systems Data Analysis Internship

**Author:** Data Analyst Intern
**Task:** 1 of 4 (selected tasks)

---

## 1. Business Problem

Telecommunications companies lose significant revenue every year when existing customers cancel
their subscriptions (churn). Before any churn driver can be analyzed or predicted, the raw
operational data must be audited and cleaned, because analysis built on unverified data produces
unreliable business decisions.

## 2. Objective

Audit the raw Telco Customer Churn dataset for missing values, duplicates, incorrect datatypes and
inconsistent categorical values, apply justified cleaning treatments, encode categorical variables
for downstream modeling, and output a cleaned dataset that Tasks 2–4 can rely on.

## 3. Dataset Overview

The dataset (`Telco_Customer_Churn_Dataset_.csv`) contains one row per customer of a telecom
company, with demographic attributes, subscribed services, account/contract information, billing
charges, and a `Churn` label indicating whether the customer left the company.

## 4. Import Libraries

In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 150)

## 5. Load Dataset

In [2]:
df = pd.read_csv('../Telco_Customer_Churn_Dataset_.csv')

print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print("\nColumn names:")
print(list(df.columns))

Number of rows: 7043
Number of columns: 21

Column names:
['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn']

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.sample(5, random_state=42)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,No,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,No,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
df.dtypes

customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

## 6. Data Quality Investigation

### 6.1 Missing values (standard nulls)

In [7]:
missing_counts = df.isnull().sum()
missing_pct = (missing_counts / len(df) * 100).round(2)
missing_summary = pd.DataFrame({'missing_count': missing_counts, 'missing_pct': missing_pct})
missing_summary[missing_summary['missing_count'] > 0].sort_values('missing_count', ascending=False)

Empty DataFrame
Columns: [missing_count, missing_pct]
Index: []

**Observation:** A standard `.isnull()` check reports **0 missing values** across all 21
columns. However, this does not necessarily mean the data is complete — some columns may contain
"hidden" missing values represented as blank strings or placeholder text rather than true `NaN`.
`TotalCharges` is investigated specifically below because it is loaded as a text column, which is
unusual for a monetary field.

### 6.2 Duplicate rows and duplicate customer IDs

In [8]:
duplicate_rows = df.duplicated().sum()
duplicate_ids = df['customerID'].duplicated().sum()

print(f"Fully duplicated rows: {duplicate_rows}")
print(f"Duplicate customerID values: {duplicate_ids}")
print(f"Unique customerID count: {df['customerID'].nunique()} out of {len(df)} rows")

Fully duplicated rows: 0
Duplicate customerID values: 0
Unique customerID count: 7043 out of 7043 rows

**Observation:** There are **0 fully duplicated rows** and **0 duplicate `customerID`**
values — every row represents a unique customer. No duplicate-removal treatment is required.

### 6.3 `TotalCharges` datatype investigation

In [9]:
print("Current dtype of TotalCharges:", df['TotalCharges'].dtype)

# Attempt numeric conversion and see which values fail to convert
totalcharges_numeric_attempt = pd.to_numeric(df['TotalCharges'], errors='coerce')
non_numeric_mask = totalcharges_numeric_attempt.isnull()

print(f"\nRows where TotalCharges cannot be converted to a number: {non_numeric_mask.sum()}")
df.loc[non_numeric_mask, ['customerID', 'tenure', 'MonthlyCharges', 'TotalCharges', 'Churn']]

Current dtype of TotalCharges: str

Rows where TotalCharges cannot be converted to a number: 11

      customerID  tenure  MonthlyCharges TotalCharges Churn
488   4472-LVYGI       0           52.55                 No
753   3115-CZMZD       0           20.25                 No
936   5709-LVOEQ       0           80.85                 No
1082  4367-NUYAO       0           25.75                 No
1340  1371-DWPAZ       0           56.05                 No
3331  7644-OMVMY       0           19.85                 No
3826  3213-VVOLG       0           25.35                 No
4380  2520-SGTTA       0           20.00                 No
5218  2923-ARZLG       0           19.70                 No
6670  4075-WKNIU       0           73.35                 No
6754  2775-SEFEE       0           61.90                 No

**Observation:** `TotalCharges` is stored as a text (`object`) column instead of a number.
When forced to numeric, **11 rows** fail to convert. Inspecting those rows shows their raw
`TotalCharges` value is an **empty string** (whitespace), and in every one of these 11 rows
**`tenure` = 0**, meaning the customer had just signed up and had not yet been billed a first full
cycle — so no total-charges figure existed yet at the time of data extraction. This is a logical,
explainable data-entry gap rather than a random data-quality error, and all 11 of these customers
have `Churn = No`.

**Why conversion cannot be done blindly:** simply calling `pd.to_numeric()` without first checking
would silently convert these blank strings to `NaN`, which is correct — but the investigation above
is required to confirm the cause is genuine "new customer, not yet billed" rather than a data-entry
error which might warrant a different treatment (e.g. supplying a default value or excluding the
customer entirely).

## 7. Missing-Value Treatment

In [10]:
# Convert TotalCharges to numeric now that the cause of the blank values is understood
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

print(f"Missing values in TotalCharges after conversion: {df['TotalCharges'].isnull().sum()}")
print(f"These correspond to customers with tenure = 0: "
      f"{(df.loc[df['TotalCharges'].isnull(), 'tenure'] == 0).all()}")

Missing values in TotalCharges after conversion: 11
These correspond to customers with tenure = 0: True

**Decision:** For these 11 zero-tenure customers, `TotalCharges` is logically **0** — they
have not been billed yet, so total historical charges are genuinely zero rather than "unknown".
Imputing with the column mean/median would fabricate a charge history these customers never had, and
dropping them would discard 11 real, valid customer records for a segment (new sign-ups) that is
analytically important for churn analysis. Therefore, the correct treatment is to **impute these 11
values with 0**, not with a mean/median and not by row deletion.

In [11]:
df['TotalCharges'] = df['TotalCharges'].fillna(0)

print(f"Missing values in TotalCharges after treatment: {df['TotalCharges'].isnull().sum()}")
print(f"TotalCharges dtype: {df['TotalCharges'].dtype}")
df['TotalCharges'].describe()

Missing values in TotalCharges after treatment: 0
TotalCharges dtype: float64

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: TotalCharges, dtype: float64

## 8. Duplicate Handling (confirmation)

In [12]:
print(f"Duplicate rows remaining: {df.duplicated().sum()}")
print(f"Duplicate customerID remaining: {df['customerID'].duplicated().sum()}")
# No removal needed - confirmed above in section 6.2

Duplicate rows remaining: 0
Duplicate customerID remaining: 0

## 9. Inconsistent / Suspicious Categorical Values

In [13]:
categorical_cols = df.select_dtypes(include='object').columns.tolist()
categorical_cols.remove('customerID')

for col in categorical_cols:
    print(f"{col}: {sorted(df[col].unique().tolist())}")

gender: ['Female', 'Male']
Partner: ['No', 'Yes']
Dependents: ['No', 'Yes']
PhoneService: ['No', 'Yes']
MultipleLines: ['No', 'No phone service', 'Yes']
InternetService: ['DSL', 'Fiber optic', 'No']
OnlineSecurity: ['No', 'No internet service', 'Yes']
OnlineBackup: ['No', 'No internet service', 'Yes']
DeviceProtection: ['No', 'No internet service', 'Yes']
TechSupport: ['No', 'No internet service', 'Yes']
StreamingTV: ['No', 'No internet service', 'Yes']
StreamingMovies: ['No', 'No internet service', 'Yes']
Contract: ['Month-to-month', 'One year', 'Two year']
PaperlessBilling: ['No', 'Yes']
PaymentMethod: ['Bank transfer (automatic)', 'Credit card (automatic)', 'Electronic check', 'Mailed check']
Churn: ['No', 'Yes']

/tmp/ipykernel_533/1085415811.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns.tolist()

**Observation:** All categorical columns contain a small, consistent set of expected
values (e.g. `Yes`/`No`, or a fixed list of service tiers). There is no inconsistent capitalization,
stray whitespace, or unexpected category — no further cleaning is required here.

`SeniorCitizen` is stored as integer `0`/`1` rather than text `Yes`/`No` like the other binary
columns — this is a datatype inconsistency relative to similar columns and is corrected below for
readability and consistency, while keeping it numeric since it is inherently binary.

In [14]:
print("SeniorCitizen unique values:", df['SeniorCitizen'].unique())
print("SeniorCitizen dtype:", df['SeniorCitizen'].dtype)
# Already numeric 0/1 - suitable as-is for modeling. Kept as-is; a readable label column is
# added separately for EDA readability in Task 2 rather than overwriting the numeric flag here.

SeniorCitizen unique values: [0 1]
SeniorCitizen dtype: int64

## 10. Numerical vs Categorical Column Summary

In [15]:
numerical_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
print("Numerical columns:", numerical_cols)
print("\nCategorical columns:", categorical_cols)
print("\nIdentifier column:", ['customerID'])
print("\nTarget column:", ['Churn'])

df[numerical_cols].describe()

Numerical columns: ['tenure', 'MonthlyCharges', 'TotalCharges']

Categorical columns: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']

Identifier column: ['customerID']

Target column: ['Churn']

            tenure  MonthlyCharges  TotalCharges
count  7043.000000     7043.000000   7043.000000
mean     32.371149       64.761692   2279.734304
std      24.559481       30.090047   2266.794470
min       0.000000       18.250000      0.000000
25%       9.000000       35.500000    398.550000
50%      29.000000       70.350000   1394.550000
75%      55.000000       89.850000   3786.600000
max      72.000000      118.750000   8684.800000

## 11. Should `customerID` Be Used as a Model Feature?

`customerID` is a unique alphanumeric identifier (verified above: 7,043 unique values for
7,043 rows, zero duplicates). It carries **no predictive signal** about customer behavior — it is
an arbitrary label generated at account creation. Including it as a model feature would:

- Add noise / a spurious high-cardinality feature that provides no real information,
- Risk the model "memorizing" IDs rather than learning genuine churn patterns,
- Provide zero business interpretability.

**Decision:** `customerID` is retained in the dataset **only as a lookup/reference key** (used in
Task 5 to identify specific high-risk customers) and is **excluded from all model features** in
Task 4.

## 12. Categorical Encoding

Encoding strategy:

- **Binary Yes/No columns** (`Partner`, `Dependents`, `PhoneService`, `PaperlessBilling`, `Churn`)
  → mapped to `1`/`0`, since two categories with a natural true/false meaning do not need extra
  dummy columns.
- **`gender`** (`Male`/`Female`) → mapped to a binary `0`/`1` flag for the same reason.
- **`SeniorCitizen`** → already numeric `0`/`1`, left as-is.
- **Multi-category columns** (`MultipleLines`, `InternetService`, `OnlineSecurity`, `OnlineBackup`,
  `DeviceProtection`, `TechSupport`, `StreamingTV`, `StreamingMovies`, `Contract`, `PaymentMethod`)
  → **one-hot encoded**, because these have 3+ unrelated categories (including "No internet
  service"/"No phone service" as a genuinely distinct category, not a missing value) and have no
  inherent order, so a single integer mapping would falsely imply rank/order between categories.
- **`customerID`** → excluded from encoding entirely (see Section 11).

A separate copy of the dataframe is encoded so that the human-readable cleaned dataset (saved at the
end of this notebook) still shows meaningful category names for reporting purposes; the fully
one-hot-encoded numeric version is produced as part of the Task 4 modeling pipeline instead, to
avoid duplicating large sparse column sets across every task's file.

In [16]:
binary_yes_no_cols = ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn']
for col in binary_yes_no_cols:
    df[col] = df[col].map({'Yes': 1, 'No': 0})

df['gender'] = df['gender'].map({'Male': 1, 'Female': 0})

print("Binary encoding applied to:", binary_yes_no_cols + ['gender'])
df[binary_yes_no_cols + ['gender', 'SeniorCitizen']].head()

Binary encoding applied to:

 ['Partner', 'Dependents', 'PhoneService', 'PaperlessBilling', 'Churn', 'gender']

   Partner  Dependents  PhoneService  PaperlessBilling  Churn  gender  SeniorCitizen
0        1           0             0                 1      0       0              0
1        0           0             1                 0      0       1              0
2        0           0             1                 1      1       1              0
3        0           0             0                 0      0       1              0
4        0           0             1                 1      1       0              0

The remaining multi-category columns are intentionally **left as text in this cleaned
dataset** (rather than one-hot encoded here) so that Tasks 2 and 3 (EDA and segmentation) can group
and plot by readable category names such as `"Month-to-month"` or `"Fiber optic"`. The one-hot
encoding required specifically for the machine-learning model is applied inside a `ColumnTransformer`
in Task 4, which is the standard, leakage-safe place to do it (fit only on the training split).

## 13. Final Cleaned Dataset

In [17]:
print("BEFORE cleaning shape (original load): (7043, 21)")
print(f"AFTER cleaning shape: {df.shape}")
print(f"\nFinal missing values: {df.isnull().sum().sum()}")
print(f"Final duplicate rows: {df.duplicated().sum()}")
print("\nFinal dtypes:")
df.dtypes

BEFORE cleaning shape (original load): (7043, 21)
AFTER cleaning shape: (7043, 21)

Final missing values: 0
Final duplicate rows: 0

Final dtypes:

customerID              str
gender                int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
PhoneService          int64
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling      int64
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                 int64
dtype: object

In [18]:
df.to_csv('Task_1_Cleaned_Dataset.csv', index=False)
print("Saved: Task_1_Cleaned_Dataset.csv")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

Saved: Task_1_Cleaned_Dataset.csv
Rows: 7043, Columns: 21

## 14. Before vs After Cleaning Summary

In [19]:
summary_table = pd.DataFrame({
    'Issue': [
        'TotalCharges stored as text',
        'TotalCharges blank values (11 rows, tenure=0)',
        'SeniorCitizen inconsistent type vs other binary cols',
        'Duplicate rows',
        'Duplicate customerID',
        'Binary Yes/No columns as text',
        'gender as text',
    ],
    'Before': [
        'object (string) dtype',
        '11 blank strings -> NaN on numeric conversion',
        'int 0/1 (inconsistent style, not an error)',
        '0 found',
        '0 found',
        'Yes / No strings',
        'Male / Female strings',
    ],
    'After': [
        'float64',
        'Imputed with 0 (new customers, not yet billed)',
        'Kept as int 0/1 (already model-ready)',
        'No action needed',
        'No action needed',
        'Mapped to 1 / 0',
        'Mapped to 1 (Male) / 0 (Female)',
    ],
})
summary_table

                                               Issue                                         Before                                           After
0                        TotalCharges stored as text                          object (string) dtype                                         float64
1      TotalCharges blank values (11 rows, tenure=0)  11 blank strings -> NaN on numeric conversion  Imputed with 0 (new customers, not yet billed)
2  SeniorCitizen inconsistent type vs other binar...     int 0/1 (inconsistent style, not an error)           Kept as int 0/1 (already model-ready)
3                                     Duplicate rows                                        0 found                                No action needed
4                               Duplicate customerID                                        0 found                                No action needed
5                      Binary Yes/No columns as text                               Yes / No strings                                 Mapped to 1 / 0
6                                     gender as text                          Male / Female strings                 Mapped to 1 (Male) / 0 (Female)

## 15. Task 1 Conclusion

The raw dataset was structurally very clean: there were **zero duplicate rows**, **zero
duplicate customer IDs**, and **zero missing values under a naive null check**. The single genuine
data-quality issue was `TotalCharges` being stored as text due to **11 blank-string values**, all
of which belonged to customers with `tenure = 0` (brand-new sign-ups not yet billed). These were
corrected by converting the column to numeric and imputing the 11 blanks with `0`, which reflects
their true billing history rather than an unknown value.

Binary categorical columns (`Partner`, `Dependents`, `PhoneService`, `PaperlessBilling`, `Churn`,
`gender`) were mapped to `1`/`0`. Multi-category service and billing columns were left as readable
text for EDA/segmentation and will be one-hot encoded inside the modeling pipeline in Task 4 to avoid
data leakage. `customerID` was confirmed to be a unique, non-predictive identifier and will be
excluded from all model features.

The cleaned dataset (`Task_1_Cleaned_Dataset.csv`, 7,043 rows × 21 columns, 0 missing values, 0
duplicates) is now ready to support the Exploratory Data Analysis (Task 2), Customer Segmentation
(Task 3), and Churn Prediction Model (Task 4) that follow.